openapi: 3.0.0
info:
  title: API SANTE CONNECT - HTTP
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Users
  - name: Cities
paths:
  /users/auth:
    post:
      tags:
        - Users
      summary: USERS - Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: user1@example.com
                password: password123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    post:
      tags:
        - Users
      summary: Users - Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ant.zdjbzd@gmail.com
                city: Paris
                password: azerty
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/infos:
    get:
      tags:
        - Users
      summary: Users - Infos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/cities:
    patch:
      tags:
        - Users
      summary: Users - City - Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Pau
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /city:
    post:
      tags:
        - Cities
      summary: Cities - Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                postal: 59000
                name: Lille
                x: 2
                'y': 29.2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
